import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET() {
  try {
    let config = await prisma.heroConfig.findFirst();
    if (!config) {
      config = await prisma.heroConfig.create({
        data: { articleSlug: 'architecture-of-silence' },
      });
    }
    return NextResponse.json({ success: true, data: config });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}

export async function PUT(req: NextRequest) {
  try {
    const body = await req.json();
    let config = await prisma.heroConfig.findFirst();
    
    // Discard fields generated by the DB or frontend
    const { id, createdAt, updatedAt, ...validData } = body;
    
    if (config) {
      config = await prisma.heroConfig.update({
        where: { id: config.id },
        data: validData,
      });
    } else {
      config = await prisma.heroConfig.create({
        data: validData as any,
      });
    }
    
    return NextResponse.json({ success: true, data: config });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
